/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    roles: Role;
    categories: Category;
    'rental-items': RentalItem;
    variations: Variation;
    bookings: Booking;
    customers: Customer;
    availability: Availability;
    plans: Plan;
    subscriptions: Subscription;
    'inventory-units': InventoryUnit;
    bundles: Bundle;
    'add-ons': AddOn;
    payments: Payment;
    'webhook-endpoints': WebhookEndpoint;
    'webhook-deliveries': WebhookDelivery;
    notifications: Notification;
    'api-keys': ApiKey;
    'audit-logs': AuditLog;
    invoices: Invoice;
    contracts: Contract;
    'contract-templates': ContractTemplate;
    'maintenance-records': MaintenanceRecord;
    'maintenance-schedules': MaintenanceSchedule;
    'email-templates': EmailTemplate;
    documents: Document;
    'signed-documents': SignedDocument;
    'stripe-webhook-events': StripeWebhookEvent;
    'platform-transactions': PlatformTransaction;
    'quote-requests': QuoteRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'rental-items': RentalItemsSelect<false> | RentalItemsSelect<true>;
    variations: VariationsSelect<false> | VariationsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    availability: AvailabilitySelect<false> | AvailabilitySelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'inventory-units': InventoryUnitsSelect<false> | InventoryUnitsSelect<true>;
    bundles: BundlesSelect<false> | BundlesSelect<true>;
    'add-ons': AddOnsSelect<false> | AddOnsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'webhook-endpoints': WebhookEndpointsSelect<false> | WebhookEndpointsSelect<true>;
    'webhook-deliveries': WebhookDeliveriesSelect<false> | WebhookDeliveriesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    contracts: ContractsSelect<false> | ContractsSelect<true>;
    'contract-templates': ContractTemplatesSelect<false> | ContractTemplatesSelect<true>;
    'maintenance-records': MaintenanceRecordsSelect<false> | MaintenanceRecordsSelect<true>;
    'maintenance-schedules': MaintenanceSchedulesSelect<false> | MaintenanceSchedulesSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'signed-documents': SignedDocumentsSelect<false> | SignedDocumentsSelect<true>;
    'stripe-webhook-events': StripeWebhookEventsSelect<false> | StripeWebhookEventsSelect<true>;
    'platform-transactions': PlatformTransactionsSelect<false> | PlatformTransactionsSelect<true>;
    'quote-requests': QuoteRequestsSelect<false> | QuoteRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'platform-settings': PlatformSetting;
  };
  globalsSelect: {
    'platform-settings': PlatformSettingsSelect<false> | PlatformSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The tenant this user belongs to (not required for super admins)
   */
  tenantId?: (number | null) | Tenant;
  /**
   * User role and permissions level
   */
  role: 'super_admin' | 'tenant_admin' | 'admin' | 'manager' | 'staff' | 'customer';
  /**
   * Whether this user account is active
   */
  isActive?: boolean | null;
  profile?: {
    /**
     * Full name
     */
    name?: string | null;
    /**
     * Phone number
     */
    phone?: string | null;
    /**
     * Profile picture
     */
    avatar?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Business or organization name
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., jump-for-joy-rentals)
   */
  slug: string;
  /**
   * Custom domain (e.g., rentals.jumpforjoy.com)
   */
  domain?: string | null;
  /**
   * Company logo for branding
   */
  logo?: (number | null) | Media;
  /**
   * Subscription plan tier
   */
  plan: 'free' | 'pro' | 'platinum';
  /**
   * Override platform fee rate (0-1). Set to 0 to exempt from fees. Leave empty to use tier-based fee.
   */
  platformFeeOverride?: number | null;
  /**
   * Stripe Connect account ID
   */
  stripeAccountId?: string | null;
  /**
   * Stripe Connect account status
   */
  stripeAccountStatus?: ('pending' | 'active' | 'restricted' | 'disabled') | null;
  /**
   * Whether Stripe onboarding is complete
   */
  stripeDetailsSubmitted?: boolean | null;
  /**
   * Whether the account can accept charges
   */
  stripeChargesEnabled?: boolean | null;
  /**
   * Whether the account can receive payouts
   */
  stripePayoutsEnabled?: boolean | null;
  /**
   * API key for widget authentication (BH-SaaS internal)
   */
  apiKey: string;
  /**
   * Tenant ID in rb-payload booking engine
   */
  rbPayloadTenantId?: number | null;
  /**
   * API key for rb-payload booking engine
   */
  rbPayloadApiKey?: string | null;
  /**
   * Status of rb-payload tenant provisioning
   */
  rbPayloadSyncStatus?: ('pending' | 'provisioned' | 'failed') | null;
  /**
   * Error message if rb-payload provisioning failed
   */
  rbPayloadSyncError?: string | null;
  /**
   * Business phone number
   */
  phone?: string | null;
  /**
   * Business email address
   */
  email?: string | null;
  /**
   * Business description for customers
   */
  description?: string | null;
  /**
   * Business address
   */
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  /**
   * Weekly business hours
   */
  businessHours?: {
    monday?: {
      enabled?: boolean | null;
      open?: string | null;
      close?: string | null;
    };
    tuesday?: {
      enabled?: boolean | null;
      open?: string | null;
      close?: string | null;
    };
    wednesday?: {
      enabled?: boolean | null;
      open?: string | null;
      close?: string | null;
    };
    thursday?: {
      enabled?: boolean | null;
      open?: string | null;
      close?: string | null;
    };
    friday?: {
      enabled?: boolean | null;
      open?: string | null;
      close?: string | null;
    };
    saturday?: {
      enabled?: boolean | null;
      open?: string | null;
      close?: string | null;
    };
    sunday?: {
      enabled?: boolean | null;
      open?: string | null;
      close?: string | null;
    };
  };
  /**
   * Service delivery area
   */
  serviceArea?: {
    /**
     * Service radius in miles/km
     */
    radius?: number | null;
    unit?: ('miles' | 'km') | null;
    /**
     * Specific ZIP codes served
     */
    zipCodes?:
      | {
          code?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Brand identity and theming
   */
  branding?: {
    /**
     * Business name for branding (overrides tenant name)
     */
    businessName?: string | null;
    /**
     * Short tagline or slogan
     */
    tagline?: string | null;
    /**
     * Primary brand color (hex)
     */
    primaryColor?: string | null;
    /**
     * Secondary brand color (hex)
     */
    secondaryColor?: string | null;
    /**
     * Accent color for buttons and CTAs (hex)
     */
    accentColor?: string | null;
    /**
     * Email header background color (hex)
     */
    emailHeaderBg?: string | null;
    /**
     * Email button color (hex)
     */
    emailButtonColor?: string | null;
    /**
     * Custom footer text for emails
     */
    emailFooter?: string | null;
    /**
     * Invoice header text
     */
    invoiceHeader?: string | null;
    /**
     * Terms & Conditions for contracts
     */
    termsAndConditions?: string | null;
    /**
     * Safety guidelines for rental agreements
     */
    safetyGuidelines?: string | null;
  };
  /**
   * Public website configuration
   */
  website?: {
    /**
     * Enable public website for this tenant
     */
    enabled?: boolean | null;
    /**
     * Website design template - choose the style that fits your brand
     */
    templateId?: ('classic' | 'modern' | 'bold' | 'playful' | 'elegant') | null;
    /**
     * Main headline on the website
     */
    heroTitle?: string | null;
    /**
     * Subheadline text
     */
    heroSubtitle?: string | null;
    /**
     * Hero background image
     */
    heroImage?: (number | null) | Media;
    /**
     * About section title
     */
    aboutTitle?: string | null;
    /**
     * About section content
     */
    aboutContent?: string | null;
    /**
     * Show services/inventory section
     */
    showServices?: boolean | null;
    /**
     * Services section title
     */
    servicesTitle?: string | null;
    /**
     * Show testimonials section
     */
    showTestimonials?: boolean | null;
    /**
     * Customer testimonials
     */
    testimonials?:
      | {
          name: string;
          content: string;
          rating?: number | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Show photo gallery section
     */
    showGallery?: boolean | null;
    /**
     * Gallery images
     */
    galleryImages?:
      | {
          image: number | Media;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Call-to-action button text
     */
    ctaText?: string | null;
    /**
     * SEO settings
     */
    seo?: {
      /**
       * Page title (defaults to business name)
       */
      title?: string | null;
      /**
       * Meta description for search engines
       */
      description?: string | null;
      /**
       * Comma-separated keywords
       */
      keywords?: string | null;
    };
  };
  /**
   * Website builder data (pages, sections, theme)
   */
  websiteBuilder?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Custom website development offering
   */
  customWebsite?: {
    /**
     * Whether tenant has requested custom website development
     */
    requested?: boolean | null;
    /**
     * Status of custom website development
     */
    status?: ('pending' | 'in_progress' | 'live') | null;
    /**
     * Date when one-time setup fee was paid
     */
    setupPaidAt?: string | null;
    /**
     * Date when monthly recurring fee started
     */
    monthlyStartedAt?: string | null;
  };
  settings?: {
    timezone?: ('America/New_York' | 'America/Chicago' | 'America/Denver' | 'America/Los_Angeles' | 'UTC') | null;
    currency?: ('USD' | 'EUR' | 'GBP' | 'CAD') | null;
    locale?: ('en-US' | 'en-GB' | 'es-ES' | 'fr-FR') | null;
    bookingSettings?: {
      /**
       * Minimum hours in advance for bookings
       */
      leadTime?: number | null;
      /**
       * Maximum days in advance for bookings
       */
      maxAdvanceBooking?: number | null;
      /**
       * Cancellation policy text shown to customers
       */
      cancellationPolicy?: string | null;
      /**
       * Bookings require manual approval
       */
      requireApproval?: boolean | null;
      /**
       * Required deposit percentage (0-100)
       */
      depositPercentage?: number | null;
    };
    /**
     * Delivery and setup settings
     */
    deliverySettings?: {
      /**
       * Maximum delivery distance in miles
       */
      deliveryRadius?: number | null;
      /**
       * Base delivery fee
       */
      baseDeliveryFee?: number | null;
      /**
       * Average setup time in minutes
       */
      setupTime?: number | null;
      /**
       * Average pickup time in minutes
       */
      pickupTime?: number | null;
    };
    /**
     * Notification preferences
     */
    notificationSettings?: {
      /**
       * Email notifications for new bookings
       */
      emailNewBooking?: boolean | null;
      /**
       * Email notifications for cancellations
       */
      emailCancellation?: boolean | null;
      /**
       * Email notifications for payments
       */
      emailPayment?: boolean | null;
      /**
       * Email reminder notifications
       */
      emailReminder?: boolean | null;
      /**
       * Daily summary email
       */
      emailDailySummary?: boolean | null;
      /**
       * In-app notifications for new bookings
       */
      inAppNewBooking?: boolean | null;
      /**
       * In-app notifications for cancellations
       */
      inAppCancellation?: boolean | null;
      /**
       * In-app notifications for payments
       */
      inAppPayment?: boolean | null;
      /**
       * In-app reminder notifications
       */
      inAppReminder?: boolean | null;
      /**
       * Hours before rental to send reminder
       */
      reminderTiming?: number | null;
    };
  };
  /**
   * Tenant account status
   */
  status: 'active' | 'suspended' | 'deleted';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Leave empty for platform-wide assets
   */
  tenantId?: (number | null) | Tenant;
  /**
   * Alt text for accessibility
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Custom roles and permissions for team members (Pro/Platinum feature)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  /**
   * The tenant this custom role belongs to
   */
  tenantId: number | Tenant;
  /**
   * Role name (e.g., "Operations Manager", "Delivery Driver")
   */
  name: string;
  /**
   * Optional description of what this role is for
   */
  description?: string | null;
  /**
   * System roles are built-in templates that cannot be deleted
   */
  isSystemRole?: boolean | null;
  /**
   * Granular permissions granted to users with this role
   */
  permissions: {
    /**
     * Permission key following resource.action pattern
     */
    key:
      | 'bookings.view'
      | 'bookings.create'
      | 'bookings.edit'
      | 'bookings.delete'
      | 'bookings.manage_payments'
      | 'inventory.view'
      | 'inventory.create'
      | 'inventory.edit'
      | 'inventory.delete'
      | 'inventory.manage_pricing'
      | 'customers.view'
      | 'customers.create'
      | 'customers.edit'
      | 'customers.delete'
      | 'customers.export'
      | 'availability.view'
      | 'availability.manage'
      | 'team.view'
      | 'team.invite'
      | 'team.edit_roles'
      | 'team.remove'
      | 'reports.view_revenue'
      | 'reports.view_customers'
      | 'reports.export'
      | 'settings.view'
      | 'settings.edit_branding'
      | 'settings.edit_booking'
      | 'settings.edit_integrations'
      | 'settings.edit_payments'
      | 'documents.view'
      | 'documents.create'
      | 'documents.delete'
      | 'contracts.view'
      | 'contracts.create'
      | 'contracts.delete';
    id?: string | null;
  }[];
  /**
   * Color for role badge in UI
   */
  color?: ('blue' | 'green' | 'purple' | 'orange' | 'pink' | 'indigo' | 'teal') | null;
  /**
   * Number of users assigned to this role (auto-calculated)
   */
  memberCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * The tenant this category belongs to
   */
  tenantId: number | Tenant;
  /**
   * Category name (e.g., "Bounce Houses", "Water Slides")
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Brief description of this category
   */
  description?: string | null;
  /**
   * Icon name (e.g., "i-lucide-castle", "i-lucide-tent")
   */
  icon?: string | null;
  /**
   * Category image (optional)
   */
  image?: (number | null) | Media;
  /**
   * Display order (lower numbers appear first)
   */
  sortOrder: number;
  /**
   * Is this category currently active?
   */
  isActive?: boolean | null;
  /**
   * Number of rental items in this category (computed)
   */
  itemCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rental-items".
 */
export interface RentalItem {
  id: number;
  /**
   * The tenant this rental item belongs to
   */
  tenantId: number | Tenant;
  /**
   * Auto-generated unique serial number for this rental item (e.g., RH-1725000000000-A7B9K)
   */
  serialNumber?: string | null;
  /**
   * Rental item name (e.g., "Princess Castle Bounce House", "Water Slide Deluxe")
   */
  name: string;
  /**
   * Detailed description of the rental item
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Legacy category field (use categoryId relationship instead)
   */
  category?:
    | (
        | 'bounce_house'
        | 'water_slide'
        | 'combo_unit'
        | 'obstacle_course'
        | 'interactive_game'
        | 'tent_canopy'
        | 'table_chair'
        | 'concession'
        | 'other'
      )
    | null;
  /**
   * Category for this rental item (recommended over legacy category field)
   */
  categoryId?: (number | null) | Category;
  /**
   * Product images (first image is primary). Upload via Bunny CDN.
   */
  images?:
    | {
        /**
         * Image URL (Bunny CDN or external)
         */
        url: string;
        /**
         * Alt text for accessibility
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  pricing: {
    /**
     * Hourly rental rate (optional)
     */
    hourlyRate?: number | null;
    /**
     * Full day rental rate
     */
    dailyRate: number;
    /**
     * Weekend rental rate (Friday-Sunday)
     */
    weekendRate?: number | null;
    /**
     * Weekly rental rate (7 days)
     */
    weeklyRate?: number | null;
  };
  dimensions?: {
    /**
     * Length in feet
     */
    length?: number | null;
    /**
     * Width in feet
     */
    width?: number | null;
    /**
     * Height in feet
     */
    height?: number | null;
  };
  /**
   * Maximum number of people/children
   */
  capacity?: number | null;
  ageRange?: {
    /**
     * Minimum age
     */
    minAge?: number | null;
    /**
     * Maximum age
     */
    maxAge?: number | null;
  };
  setupRequirements?: {
    /**
     * Space requirements (e.g., "15x15 flat area")
     */
    spaceRequired?: string | null;
    /**
     * Requires electrical outlet
     */
    powerRequired?: boolean | null;
    /**
     * Requires water hookup
     */
    waterRequired?: boolean | null;
    /**
     * Suitable surface types
     */
    surfaceType?: ('grass' | 'concrete' | 'asphalt' | 'indoor' | 'any') | null;
    /**
     * Additional setup instructions
     */
    setupNotes?: string | null;
  };
  /**
   * Number of units available
   */
  quantity?: number | null;
  /**
   * Is this item currently available for rental?
   */
  isActive?: boolean | null;
  /**
   * Feature this item on homepage
   */
  featured?: boolean | null;
  /**
   * Tags for filtering (e.g., "outdoor", "princess theme", "wet")
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ID of corresponding service in rb-payload (for 2-way sync)
   */
  rbPayloadServiceId?: number | null;
  /**
   * Status of sync with rb-payload
   */
  syncStatus?: ('pending' | 'synced' | 'failed' | 'out_of_sync') | null;
  /**
   * Last successful sync with rb-payload
   */
  lastSyncedAt?: string | null;
  /**
   * Last sync error message
   */
  syncError?: string | null;
  /**
   * Does this item have variations (size, color, theme, etc.)?
   */
  hasVariations?: boolean | null;
  /**
   * Available variation attributes and their possible values
   */
  variationAttributes?:
    | {
        /**
         * Attribute name (e.g., "Size", "Theme", "Color")
         */
        name: string;
        /**
         * Available values for this attribute
         */
        values: {
          value: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Date of last maintenance/inspection
   */
  lastMaintenanceDate?: string | null;
  /**
   * Date when next maintenance is due
   */
  nextMaintenanceDate?: string | null;
  /**
   * Current maintenance status
   */
  maintenanceStatus?: ('up_to_date' | 'due_soon' | 'overdue') | null;
  /**
   * General maintenance notes and history
   */
  maintenanceNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variations".
 */
export interface Variation {
  id: number;
  /**
   * The tenant this variation belongs to
   */
  tenantId: number | Tenant;
  /**
   * The parent rental item this variation belongs to
   */
  rentalItemId: number | RentalItem;
  /**
   * Variation name (e.g., "Large Blue Theme", "Medium Princess")
   */
  name: string;
  /**
   * Stock keeping unit (SKU) - must be unique within tenant
   */
  sku: string;
  /**
   * Variation attributes that differentiate this from the parent item
   */
  attributes: {
    /**
     * Attribute name (e.g., "Size", "Theme", "Color")
     */
    name: string;
    /**
     * Attribute value (e.g., "Large", "Princess", "Blue")
     */
    value: string;
    id?: string | null;
  }[];
  /**
   * How pricing is calculated for this variation
   */
  pricingType: 'same_as_parent' | 'adjustment' | 'override';
  /**
   * Amount to add/subtract from parent price (use negative for discount)
   */
  priceAdjustment?: number | null;
  /**
   * Custom pricing for this variation (overrides parent entirely)
   */
  overridePrice?: {
    /**
     * Hourly rental rate
     */
    hourlyRate?: number | null;
    /**
     * Daily rental rate
     */
    dailyRate?: number | null;
    /**
     * Weekend rental rate
     */
    weekendRate?: number | null;
    /**
     * Weekly rental rate
     */
    weeklyRate?: number | null;
  };
  /**
   * Number of units available for this variation
   */
  quantity: number;
  /**
   * Track inventory for this variation separately
   */
  trackInventory?: boolean | null;
  /**
   * Optional images for this variation (if empty, uses parent item images)
   */
  images?:
    | {
        /**
         * Image URL (Bunny CDN or external)
         */
        url: string;
        /**
         * Alt text for accessibility
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Variation status
   */
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  tenantId: number | Tenant;
  /**
   * Items included in this booking
   */
  rentalItems: {
    /**
     * The rental item
     */
    rentalItemId: number | RentalItem;
    /**
     * Number of this item
     */
    quantity: number;
    /**
     * Price for this item
     */
    price: number;
    id?: string | null;
  }[];
  /**
   * Add-on items included in this booking
   */
  addOns?:
    | {
        /**
         * Add-on name
         */
        name: string;
        /**
         * Add-on price
         */
        price: number;
        /**
         * Quantity of this add-on
         */
        quantity: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Customer who made the booking
   */
  customerId: number | Customer;
  /**
   * Rental start date and time
   */
  startDate: string;
  /**
   * Rental end date and time
   */
  endDate: string;
  /**
   * Preferred delivery time (e.g., 9:00 AM)
   */
  deliveryTime?: string | null;
  /**
   * Preferred pickup time (e.g., 5:00 PM)
   */
  pickupTime?: string | null;
  deliveryAddress: {
    /**
     * Delivery street address
     */
    street: string;
    /**
     * City
     */
    city: string;
    /**
     * State/Province
     */
    state: string;
    /**
     * ZIP/Postal code
     */
    zipCode: string;
    /**
     * Special delivery/setup instructions
     */
    specialInstructions?: string | null;
  };
  /**
   * Booking status
   */
  status: 'pending' | 'confirmed' | 'preparing' | 'in_route' | 'delivered' | 'picked_up' | 'completed' | 'cancelled';
  /**
   * Total rental price
   */
  totalPrice: number;
  /**
   * Deposit amount paid
   */
  depositPaid?: number | null;
  /**
   * Remaining balance due
   */
  balanceDue?: number | null;
  /**
   * Payment status
   */
  paymentStatus?: ('unpaid' | 'deposit_paid' | 'paid_full' | 'refunded') | null;
  /**
   * Special instructions or notes
   */
  notes?: string | null;
  /**
   * Internal staff notes (not visible to customer)
   */
  internalNotes?: string | null;
  /**
   * Whether a 24-hour booking reminder has been sent
   */
  reminderSent?: boolean | null;
  /**
   * Timestamp when reminder was sent
   */
  reminderSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  tenantId: number | Tenant;
  /**
   * Customer full name
   */
  name: string;
  /**
   * Customer email address
   */
  email: string;
  /**
   * Customer phone number
   */
  phone: string;
  address?: {
    /**
     * Street address
     */
    street?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State/Province
     */
    state?: string | null;
    /**
     * ZIP/Postal code
     */
    zipCode?: string | null;
  };
  /**
   * Internal notes about this customer
   */
  notes?: string | null;
  /**
   * Tags for customer segmentation (e.g., "VIP", "Regular", "Corporate")
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Total number of bookings
   */
  totalBookings?: number | null;
  /**
   * Customer ID in rb-payload booking system
   */
  rbPayloadCustomerId?: number | null;
  /**
   * Sync status with rb-payload
   */
  syncStatus?: ('pending' | 'synced' | 'failed' | 'out_of_sync') | null;
  /**
   * Last successful sync timestamp
   */
  lastSyncedAt?: string | null;
  /**
   * Last sync error message
   */
  syncError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage blackout dates and maintenance windows for rental items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability".
 */
export interface Availability {
  id: number;
  /**
   * The tenant this availability rule belongs to
   */
  tenantId: number | Tenant;
  /**
   * The rental item this blackout applies to
   */
  rentalItemId: number | RentalItem;
  /**
   * Blackout start date and time
   */
  startDate: string;
  /**
   * Blackout end date and time
   */
  endDate: string;
  /**
   * Reason for unavailability
   */
  reason: 'maintenance' | 'repair' | 'booked' | 'seasonal' | 'other';
  /**
   * Additional notes about this blackout period
   */
  notes?: string | null;
  /**
   * Is this blackout currently active?
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  /**
   * Plan name (e.g., "Free", "Pro", "Enterprise")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "free", "pro", "enterprise")
   */
  slug: string;
  /**
   * Monthly price in cents (e.g., 2900 for $29.00)
   */
  price: number;
  /**
   * Transaction fee percentage (e.g., 6 for 6%)
   */
  transactionFee: number;
  /**
   * List of features included in this plan
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  limits: {
    /**
     * Maximum number of rental items allowed
     */
    maxItems: number;
    /**
     * Maximum number of bookings per month
     */
    maxBookings: number;
    /**
     * Maximum number of team members allowed
     */
    maxUsers: number;
  };
  /**
   * Feature toggles for this plan
   */
  featureFlags?: {
    /**
     * Access to website builder
     */
    websiteBuilder?: boolean | null;
    /**
     * Access to custom roles and permissions
     */
    customRoles?: boolean | null;
    /**
     * Can request custom website development
     */
    customWebsite?: boolean | null;
    /**
     * Access to priority support
     */
    prioritySupport?: boolean | null;
    /**
     * Remove BouncePro branding
     */
    whiteLabel?: boolean | null;
    /**
     * Access to API keys and webhooks
     */
    apiAccess?: boolean | null;
  };
  /**
   * Stripe Price ID (e.g., price_xxx)
   */
  stripePriceId?: string | null;
  /**
   * Is this plan available for new signups?
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  /**
   * The tenant this subscription belongs to
   */
  tenantId: number | Tenant;
  /**
   * Subscription plan
   */
  plan: number | Plan;
  /**
   * Subscription status
   */
  status: 'active' | 'canceled' | 'past_due' | 'trialing' | 'incomplete' | 'incomplete_expired' | 'unpaid';
  /**
   * Stripe subscription ID
   */
  stripeSubscriptionId?: string | null;
  /**
   * Stripe customer ID for the tenant
   */
  stripeCustomerId?: string | null;
  /**
   * Stripe price ID for the subscription plan
   */
  stripePriceId?: string | null;
  /**
   * Current billing period start date
   */
  currentPeriodStart?: string | null;
  /**
   * Current billing period end date
   */
  currentPeriodEnd?: string | null;
  /**
   * Cancel subscription at end of current period
   */
  cancelAtPeriodEnd?: boolean | null;
  /**
   * Date when subscription was canceled
   */
  canceledAt?: string | null;
  /**
   * Trial period start date
   */
  trialStart?: string | null;
  /**
   * Trial period end date
   */
  trialEnd?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-units".
 */
export interface InventoryUnit {
  id: number;
  /**
   * The tenant this inventory unit belongs to
   */
  tenantId: number | Tenant;
  /**
   * The rental item this unit represents
   */
  rentalItem: number | RentalItem;
  /**
   * Unit identifier (e.g., "Unit #1", "Castle A")
   */
  label: string;
  /**
   * Manufacturer serial number
   */
  serialNumber?: string | null;
  /**
   * Barcode for scanning
   */
  barcode?: string | null;
  /**
   * Current status of the unit
   */
  status: 'available' | 'rented' | 'maintenance' | 'retired';
  /**
   * Physical condition of the unit
   */
  condition: 'excellent' | 'good' | 'fair' | 'poor';
  /**
   * General notes about this unit
   */
  notes?: string | null;
  /**
   * Date of purchase
   */
  purchaseDate?: string | null;
  /**
   * Purchase price (for asset tracking)
   */
  purchasePrice?: number | null;
  /**
   * Date of last maintenance/inspection
   */
  lastMaintenanceDate?: string | null;
  /**
   * Date when next maintenance is due
   */
  nextMaintenanceDate?: string | null;
  /**
   * Current maintenance status
   */
  maintenanceStatus?: ('up_to_date' | 'due_soon' | 'overdue') | null;
  /**
   * Maintenance notes specific to this unit
   */
  maintenanceNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bundles".
 */
export interface Bundle {
  id: number;
  /**
   * The tenant this bundle belongs to
   */
  tenantId: number | Tenant;
  /**
   * Bundle name (e.g., "Birthday Party Package", "Ultimate Party Bundle")
   */
  name: string;
  /**
   * Detailed description of the bundle
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Items included in this bundle
   */
  items: {
    /**
     * Rental item included in bundle
     */
    rentalItem: number | RentalItem;
    /**
     * Quantity of this item
     */
    quantity: number;
    id?: string | null;
  }[];
  pricing: {
    /**
     * Pricing strategy for this bundle
     */
    type: 'fixed' | 'calculated' | 'discounted';
    /**
     * Fixed price (if pricing type is "fixed")
     */
    fixedPrice?: number | null;
    /**
     * Discount percentage (if pricing type is "discounted")
     */
    discountPercent?: number | null;
  };
  /**
   * Bundle image
   */
  image?: (number | null) | Media;
  /**
   * Feature this bundle on homepage
   */
  featured?: boolean | null;
  /**
   * Is this bundle currently available?
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "add-ons".
 */
export interface AddOn {
  id: number;
  /**
   * The tenant this add-on belongs to
   */
  tenantId: number | Tenant;
  /**
   * Add-on name (e.g., "Delivery", "Setup", "Generator Rental")
   */
  name: string;
  /**
   * Description of the add-on service
   */
  description?: string | null;
  /**
   * Icon class name (e.g., i-lucide-truck)
   */
  icon?: string | null;
  /**
   * Category for organizing add-ons
   */
  category?: ('delivery' | 'setup' | 'equipment' | 'service' | 'other') | null;
  pricing: {
    /**
     * Pricing calculation method
     */
    type: 'fixed' | 'perItem' | 'perDay';
    /**
     * Price amount
     */
    amount: number;
  };
  /**
   * Is this add-on required for all bookings?
   */
  required?: boolean | null;
  /**
   * Is this add-on currently available?
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  /**
   * The tenant this payment belongs to
   */
  tenantId: number | Tenant;
  /**
   * The booking this payment is for
   */
  booking: number | Booking;
  /**
   * Payment amount in cents (e.g., 5000 for $50.00)
   */
  amount: number;
  /**
   * Currency code
   */
  currency?: string | null;
  /**
   * Payment status
   */
  status: 'pending' | 'processing' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded';
  /**
   * Amount refunded in cents (for partial refunds)
   */
  refundAmount?: number | null;
  /**
   * Reason for refund
   */
  refundReason?: string | null;
  /**
   * Stripe Payment Intent ID
   */
  stripePaymentIntentId?: string | null;
  /**
   * Stripe Checkout Session ID
   */
  stripeCheckoutSessionId?: string | null;
  /**
   * Stripe Charge ID
   */
  stripeChargeId?: string | null;
  /**
   * Stripe Refund ID (if payment was refunded)
   */
  stripeRefundId?: string | null;
  /**
   * Platform fee in cents (deducted from payment)
   */
  platformFee?: number | null;
  /**
   * Stripe processing fee in cents (typically 2.9% + 30¢)
   */
  stripeFee?: number | null;
  /**
   * Platform fee percentage at time of transaction
   */
  platformFeePercent?: number | null;
  /**
   * Net amount tenant receives in cents (after platform fee)
   */
  netAmount?: number | null;
  /**
   * Type of payment
   */
  type: 'deposit' | 'balance' | 'full' | 'refund';
  /**
   * Additional payment metadata
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-endpoints".
 */
export interface WebhookEndpoint {
  id: number;
  /**
   * The tenant this webhook endpoint belongs to
   */
  tenantId: number | Tenant;
  /**
   * Friendly name for this webhook endpoint
   */
  name: string;
  /**
   * Webhook endpoint URL (must be HTTPS)
   */
  url: string;
  /**
   * Webhook signing secret for verification (auto-generated)
   */
  secret: string;
  /**
   * Events that will trigger this webhook
   */
  events: {
    event:
      | 'booking.created'
      | 'booking.updated'
      | 'booking.confirmed'
      | 'booking.cancelled'
      | 'booking.delivered'
      | 'booking.completed'
      | 'payment.succeeded'
      | 'payment.failed'
      | 'payment.refunded'
      | 'customer.created'
      | 'customer.updated'
      | 'inventory.low'
      | 'maintenance.due';
    id?: string | null;
  }[];
  /**
   * Enable or disable this webhook endpoint
   */
  isActive?: boolean | null;
  /**
   * Last time a webhook was delivered to this endpoint
   */
  lastDeliveryAt?: string | null;
  /**
   * Status of the last delivery attempt
   */
  lastDeliveryStatus?: ('success' | 'failed') | null;
  /**
   * Number of consecutive failed deliveries
   */
  failedDeliveriesCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Webhook delivery logs and retry tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-deliveries".
 */
export interface WebhookDelivery {
  id: number;
  /**
   * The webhook endpoint this delivery was sent to
   */
  endpointId: number | WebhookEndpoint;
  /**
   * The tenant this delivery belongs to
   */
  tenantId: number | Tenant;
  /**
   * The event that triggered this webhook
   */
  event: string;
  /**
   * The data that was sent in the webhook
   */
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Current status of this delivery
   */
  status: 'pending' | 'delivered' | 'failed' | 'retrying';
  /**
   * Number of delivery attempts
   */
  attempts?: number | null;
  /**
   * Maximum number of retry attempts
   */
  maxAttempts?: number | null;
  /**
   * When to attempt the next retry
   */
  nextRetryAt?: string | null;
  /**
   * Response from the webhook endpoint
   */
  response?: {
    /**
     * HTTP status code
     */
    statusCode?: number | null;
    /**
     * Response body (truncated to 1000 chars)
     */
    body?: string | null;
    /**
     * Response headers
     */
    headers?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Error message if delivery failed
   */
  error?: string | null;
  /**
   * When the webhook was successfully delivered
   */
  deliveredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * The tenant this notification belongs to
   */
  tenantId: number | Tenant;
  /**
   * User to notify (leave empty for all users in tenant)
   */
  user?: (number | null) | User;
  /**
   * Type of notification
   */
  type:
    | 'booking_created'
    | 'booking_confirmed'
    | 'booking_cancelled'
    | 'payment_received'
    | 'payment_failed'
    | 'reminder'
    | 'system';
  /**
   * Notification title
   */
  title: string;
  /**
   * Notification message
   */
  message: string;
  /**
   * Has this notification been read?
   */
  read?: boolean | null;
  /**
   * Additional data (e.g., booking ID, payment amount)
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  /**
   * The tenant this API key belongs to
   */
  tenantId: number | Tenant;
  /**
   * A descriptive name for this API key
   */
  name: string;
  /**
   * The API key value (only shown once at creation)
   */
  key: string;
  /**
   * First 12 characters of the key for identification
   */
  keyPrefix?: string | null;
  /**
   * When this API key was last used
   */
  lastUsed?: string | null;
  /**
   * When this API key was last rotated
   */
  lastRotatedAt?: string | null;
  /**
   * Is this API key active?
   */
  isActive?: boolean | null;
  /**
   * Access level for this API key
   */
  scopeType: 'full_access' | 'read_only' | 'booking_management' | 'custom';
  /**
   * Computed scopes based on scope type (stored as JSON array)
   */
  scopes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional expiration date for this API key
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit trail of all system actions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  /**
   * Type of action performed
   */
  action: 'create' | 'update' | 'delete' | 'login' | 'logout' | 'api_call';
  /**
   * Collection name that was affected
   */
  collection: string;
  /**
   * ID of the affected document
   */
  documentId: string;
  /**
   * User who performed the action
   */
  userId?: (number | null) | User;
  /**
   * Tenant context for this action
   */
  tenantId?: (number | null) | Tenant;
  /**
   * Before/after data for updates, full document for create/delete
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Additional metadata (IP address, user agent, etc.)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * When this action occurred
   */
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  tenantId: number | Tenant;
  /**
   * Auto-generated invoice number (e.g., INV-2025-001)
   */
  invoiceNumber: string;
  /**
   * Related booking
   */
  bookingId: number | Booking;
  /**
   * Customer this invoice is for
   */
  customerId: number | Customer;
  lineItems: {
    /**
     * Item description
     */
    description: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Price per unit
     */
    unitPrice: number;
    /**
     * Line item total
     */
    total: number;
    id?: string | null;
  }[];
  /**
   * Subtotal before tax and discounts
   */
  subtotal: number;
  /**
   * Tax amount
   */
  taxAmount?: number | null;
  /**
   * Discount amount
   */
  discountAmount?: number | null;
  /**
   * Total amount
   */
  totalAmount: number;
  /**
   * Invoice status
   */
  status: 'draft' | 'sent' | 'paid' | 'void';
  /**
   * Payment due date
   */
  dueDate?: string | null;
  /**
   * Date payment was received
   */
  paidAt?: string | null;
  /**
   * URL to generated PDF document
   */
  pdfUrl?: string | null;
  /**
   * Additional notes or payment terms
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts".
 */
export interface Contract {
  id: number;
  tenantId: number | Tenant;
  /**
   * Auto-generated contract number (e.g., CTR-2025-001)
   */
  contractNumber?: string | null;
  /**
   * Related booking (optional for standalone waivers)
   */
  bookingId?: (number | null) | Booking;
  /**
   * Customer signing this contract
   */
  customerId: number | Customer;
  /**
   * Contract type
   */
  type: 'rental-agreement' | 'liability-waiver' | 'damage-policy' | 'safety-rules' | 'weather-policy' | 'custom';
  /**
   * Contract terms and conditions
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Contract status
   */
  status: 'draft' | 'sent' | 'signed' | 'void';
  /**
   * Date contract was sent to customer
   */
  sentAt?: string | null;
  /**
   * Date contract was signed
   */
  signedAt?: string | null;
  /**
   * URL to digital signature image
   */
  signatureUrl?: string | null;
  /**
   * Name of person who signed
   */
  signerName?: string | null;
  /**
   * IP address of signer (for verification)
   */
  signerIP?: string | null;
  /**
   * URL to generated PDF document
   */
  pdfUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable contract and document templates
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-templates".
 */
export interface ContractTemplate {
  id: number;
  /**
   * Leave empty for platform-wide default templates, or set to make it tenant-specific
   */
  tenantId?: (number | null) | Tenant;
  /**
   * Template name (e.g., "Standard Rental Agreement")
   */
  name: string;
  /**
   * Type of contract template
   */
  templateType:
    | 'rental-agreement'
    | 'liability-waiver'
    | 'damage-policy'
    | 'safety-rules'
    | 'weather-policy'
    | 'custom';
  /**
   * Brief description of what this template is for
   */
  description?: string | null;
  /**
   * Template content. Use {{variableName}} for dynamic fields like {{customerName}}, {{itemName}}, {{startDate}}, etc.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Available variables that can be used in the template (auto-populated)
   */
  variables?:
    | {
        key: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Platform-wide default template (only super_admins can create/edit default templates)
   */
  isDefault?: boolean | null;
  /**
   * Whether this contract requires customer signature
   */
  requiresSignature?: boolean | null;
  /**
   * Active templates are available for use
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-records".
 */
export interface MaintenanceRecord {
  id: number;
  /**
   * The tenant this maintenance record belongs to
   */
  tenantId: number | Tenant;
  /**
   * The rental item being maintained
   */
  rentalItem: number | RentalItem;
  /**
   * Specific unit if tracking individual units (optional)
   */
  inventoryUnit?: (number | null) | InventoryUnit;
  /**
   * Type of maintenance performed
   */
  type: 'inspection' | 'cleaning' | 'repair' | 'replacement' | 'certification';
  /**
   * Description of the maintenance work
   */
  description: string;
  /**
   * When the maintenance was scheduled
   */
  scheduledDate: string;
  /**
   * When the maintenance was actually completed
   */
  completedDate?: string | null;
  /**
   * Current status of the maintenance
   */
  status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
  /**
   * Name of staff member or vendor who performed the maintenance
   */
  performedBy: string;
  /**
   * Cost of maintenance (parts + labor)
   */
  cost?: number | null;
  /**
   * Detailed notes about the maintenance work
   */
  notes?: string | null;
  /**
   * Checklist items completed during maintenance
   */
  checklist?:
    | {
        task: string;
        completed?: boolean | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Photos documenting the maintenance
   */
  photos?:
    | {
        /**
         * Photo URL (before/after photos)
         */
        url: string;
        /**
         * Photo description
         */
        caption?: string | null;
        type?: ('before' | 'after' | 'during') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Related documents (certificates, receipts, etc.)
   */
  documents?:
    | {
        /**
         * Document URL (certificates, receipts, etc.)
         */
        url: string;
        name: string;
        type?: ('certificate' | 'receipt' | 'invoice' | 'report' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When the next maintenance is recommended
   */
  nextMaintenanceDate?: string | null;
  /**
   * Blackout ID in rb-payload booking system
   */
  rbPayloadBlackoutId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-schedules".
 */
export interface MaintenanceSchedule {
  id: number;
  /**
   * The tenant this maintenance schedule belongs to
   */
  tenantId: number | Tenant;
  /**
   * The rental item this schedule applies to
   */
  rentalItem: number | RentalItem;
  /**
   * Schedule name (e.g., "Monthly Inspection", "Annual Certification")
   */
  name: string;
  /**
   * How often maintenance should occur
   */
  frequency: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'annually' | 'after_x_rentals';
  /**
   * Frequency interval (e.g., every 2 weeks, after 10 rentals)
   */
  frequencyValue?: number | null;
  /**
   * Type of maintenance to perform
   */
  maintenanceType: 'inspection' | 'cleaning' | 'repair' | 'certification';
  /**
   * Checklist of tasks to perform during maintenance
   */
  checklist?:
    | {
        /**
         * Task description
         */
        task: string;
        /**
         * Is this task required?
         */
        required?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Detailed instructions for performing the maintenance
   */
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Estimated duration in minutes
   */
  estimatedDuration?: number | null;
  /**
   * Send reminder X days before due date
   */
  reminderDaysBefore?: number | null;
  /**
   * Is this schedule currently active?
   */
  isActive?: boolean | null;
  /**
   * When was maintenance last completed?
   */
  lastCompletedDate?: string | null;
  /**
   * When is the next maintenance due? (auto-calculated)
   */
  nextDueDate?: string | null;
  /**
   * Number of rentals since last maintenance (for rental-based schedules)
   */
  rentalCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customize email templates for your business
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  /**
   * The tenant this template belongs to
   */
  tenantId: number | Tenant;
  /**
   * Which template type to customize
   */
  templateKey:
    | 'BOOKING_CONFIRMATION'
    | 'BOOKING_REMINDER'
    | 'BOOKING_CANCELLED'
    | 'PAYMENT_RECEIVED'
    | 'PASSWORD_RESET'
    | 'WELCOME';
  /**
   * Display name for this template
   */
  name: string;
  /**
   * Email subject line (supports variables like {{customerName}})
   */
  subject: string;
  /**
   * HTML email body (supports variables like {{customerName}}, {{bookingId}}, etc.)
   */
  htmlBody: string;
  /**
   * Plain text version (optional, auto-generated from HTML if empty)
   */
  textBody?: string | null;
  /**
   * Whether to use this custom template instead of the default
   */
  isActive?: boolean | null;
  /**
   * Available template variables (auto-populated based on template type)
   */
  variables?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Document templates for terms, waivers, and contracts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Internal name for this document
   */
  title: string;
  /**
   * The type of document
   */
  type: 'terms' | 'waiver' | 'contract' | 'policy';
  /**
   * Document content. Use merge fields like {{customer.name}} for dynamic content.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * If checked, customers must provide a signature
   */
  requiresSignature?: boolean | null;
  /**
   * Use this as the default document for its type
   */
  isDefault?: boolean | null;
  /**
   * Whether this document is currently in use
   */
  isActive?: boolean | null;
  /**
   * Document version number
   */
  version?: number | null;
  /**
   * When this version becomes effective
   */
  effectiveDate?: string | null;
  /**
   * The tenant this document belongs to
   */
  tenantId: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Signed document records with customer signatures
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signed-documents".
 */
export interface SignedDocument {
  id: number;
  displayTitle?: string | null;
  /**
   * The original document template
   */
  document: number | Document;
  /**
   * Type of document signed
   */
  documentType?: ('terms' | 'waiver' | 'contract' | 'policy') | null;
  /**
   * Version of the document at time of signing
   */
  documentVersion?: number | null;
  /**
   * Associated booking (if applicable)
   */
  booking?: (number | null) | Booking;
  /**
   * Customer who signed
   */
  customer?: (number | null) | Customer;
  signerInfo: {
    /**
     * Full legal name as entered by signer
     */
    signerName: string;
    /**
     * Email address of signer
     */
    signerEmail?: string | null;
    /**
     * Phone number of signer
     */
    signerPhone?: string | null;
  };
  /**
   * Name that appears in the signature
   */
  signerName: string;
  /**
   * Snapshot of document content at time of signing with merge fields replaced
   */
  signedContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  signature: {
    type: 'drawn' | 'typed';
    /**
     * Base64 image data for drawn signatures, or text for typed
     */
    data: string;
    /**
     * Font used for typed signatures
     */
    fontFamily?: string | null;
  };
  metadata: {
    /**
     * Timestamp when document was signed
     */
    signedAt: string;
    /**
     * IP address of signer
     */
    ipAddress?: string | null;
    /**
     * Browser/device information
     */
    userAgent?: string | null;
    /**
     * Signer confirmed agreement to terms
     */
    consentGiven?: boolean | null;
  };
  signedAt?: string | null;
  /**
   * Current status of this signed document
   */
  status?: ('valid' | 'superseded' | 'revoked') | null;
  /**
   * The tenant this signed document belongs to
   */
  tenantId: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Processed Stripe webhook events for replay attack prevention
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-webhook-events".
 */
export interface StripeWebhookEvent {
  id: number;
  /**
   * Unique Stripe event ID (evt_xxx)
   */
  stripeEventId: string;
  /**
   * Stripe event type (e.g., checkout.session.completed)
   */
  eventType: string;
  /**
   * When this event was successfully processed
   */
  processedAt: string;
  /**
   * When Stripe created this event (used for timestamp validation)
   */
  eventCreatedAt: string;
  /**
   * Optional metadata about the event processing
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Platform fee records for tax reporting and revenue tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-transactions".
 */
export interface PlatformTransaction {
  id: number;
  /**
   * Type of financial transaction
   */
  type: 'booking_payment' | 'subscription_payment' | 'refund' | 'payout' | 'adjustment';
  /**
   * Tenant this transaction belongs to
   */
  tenantId: number | Tenant;
  /**
   * Related booking (for booking payments)
   */
  bookingId?: (number | null) | Booking;
  /**
   * Related subscription (for subscription payments)
   */
  subscriptionId?: (number | null) | Subscription;
  /**
   * For refunds: links to the original payment for audit trail
   */
  originalTransactionId?: (number | null) | PlatformTransaction;
  /**
   * Stripe Payment Intent ID (pi_xxx)
   */
  stripePaymentIntentId?: string | null;
  /**
   * Stripe Charge ID (ch_xxx)
   */
  stripeChargeId?: string | null;
  /**
   * Stripe Transfer ID for Connect payouts (tr_xxx)
   */
  stripeTransferId?: string | null;
  /**
   * Total payment amount in cents
   */
  grossAmount: number;
  /**
   * Stripe processing fee in cents (typically 2.9% + 30¢)
   */
  stripeFee: number;
  /**
   * Our platform fee in cents
   */
  platformFee: number;
  /**
   * Platform fee percentage at time of transaction (e.g., 6 for 6%)
   */
  platformFeePercent: number;
  /**
   * Amount tenant receives after all fees (in cents)
   */
  netAmount: number;
  /**
   * Current status of the transaction
   */
  status: 'pending' | 'completed' | 'refunded' | 'partially_refunded' | 'failed';
  /**
   * Total amount refunded in cents (for partial refunds)
   */
  refundedAmount?: number | null;
  /**
   * When the refund was processed
   */
  refundedAt?: string | null;
  /**
   * YYYY-MM format for monthly revenue reports
   */
  periodMonth?: string | null;
  /**
   * Year for annual reports
   */
  periodYear?: number | null;
  /**
   * Tax year for 1099-K reporting (may differ from calendar year)
   */
  taxYear?: number | null;
  /**
   * Additional Stripe metadata and context
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Internal notes (for adjustments or manual entries)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer quote requests for custom events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests".
 */
export interface QuoteRequest {
  id: number;
  /**
   * Tenant this quote belongs to
   */
  tenantId: number | Tenant;
  status: 'pending' | 'responded' | 'converted' | 'declined' | 'expired';
  /**
   * Customer full name
   */
  customerName: string;
  /**
   * Customer email address
   */
  customerEmail: string;
  /**
   * Customer phone number
   */
  customerPhone?: string | null;
  /**
   * Type of event (Birthday, Corporate, Wedding, etc.)
   */
  eventType: string;
  /**
   * Date of the event
   */
  eventDate: string;
  /**
   * Event start time (HH:MM)
   */
  eventStartTime?: string | null;
  /**
   * Event end time (HH:MM)
   */
  eventEndTime?: string | null;
  /**
   * Expected number of guests
   */
  guestCount?: number | null;
  /**
   * Indoor or outdoor venue
   */
  venueType?: ('indoor' | 'outdoor') | null;
  /**
   * Age range of guests (e.g., "5-12 years")
   */
  ageRange?: string | null;
  /**
   * How the equipment will be obtained
   */
  fulfillmentType?: ('delivery' | 'pickup') | null;
  /**
   * Delivery address (if delivery selected)
   */
  deliveryAddress?: string | null;
  /**
   * Customer's budget range (e.g., "$200-$400")
   */
  budgetRange?: string | null;
  /**
   * Array of products/items requested (JSON)
   */
  productsRequested?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Additional services requested (setup, generators, etc.)
   */
  additionalServices?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Special requests or notes from customer
   */
  specialRequests?: string | null;
  /**
   * File attachments (images, documents)
   */
  attachments?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Admin response to the quote request
   */
  response?: {
    /**
     * Quoted total amount in cents
     */
    totalAmount?: number | null;
    /**
     * Message to customer
     */
    message?: string | null;
    /**
     * Quote validity in days
     */
    validityDays?: number | null;
    /**
     * Terms and conditions for this quote
     */
    termsConditions?: string | null;
    /**
     * When the response was sent
     */
    respondedAt?: string | null;
    /**
     * Staff member who responded
     */
    respondedBy?: (number | null) | User;
  };
  /**
   * Internal notes (not visible to customer)
   */
  adminNotes?: string | null;
  /**
   * Booking created from this quote
   */
  convertedBookingId?: (number | null) | Booking;
  /**
   * How this quote request came in
   */
  source?: ('website' | 'phone' | 'email' | 'walkin' | 'referral') | null;
  /**
   * IP address of submitter
   */
  clientIP?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'rental-items';
        value: number | RentalItem;
      } | null)
    | ({
        relationTo: 'variations';
        value: number | Variation;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'availability';
        value: number | Availability;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'inventory-units';
        value: number | InventoryUnit;
      } | null)
    | ({
        relationTo: 'bundles';
        value: number | Bundle;
      } | null)
    | ({
        relationTo: 'add-ons';
        value: number | AddOn;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'webhook-endpoints';
        value: number | WebhookEndpoint;
      } | null)
    | ({
        relationTo: 'webhook-deliveries';
        value: number | WebhookDelivery;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'contracts';
        value: number | Contract;
      } | null)
    | ({
        relationTo: 'contract-templates';
        value: number | ContractTemplate;
      } | null)
    | ({
        relationTo: 'maintenance-records';
        value: number | MaintenanceRecord;
      } | null)
    | ({
        relationTo: 'maintenance-schedules';
        value: number | MaintenanceSchedule;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: number | EmailTemplate;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'signed-documents';
        value: number | SignedDocument;
      } | null)
    | ({
        relationTo: 'stripe-webhook-events';
        value: number | StripeWebhookEvent;
      } | null)
    | ({
        relationTo: 'platform-transactions';
        value: number | PlatformTransaction;
      } | null)
    | ({
        relationTo: 'quote-requests';
        value: number | QuoteRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  tenantId?: T;
  role?: T;
  isActive?: T;
  profile?:
    | T
    | {
        name?: T;
        phone?: T;
        avatar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenantId?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  logo?: T;
  plan?: T;
  platformFeeOverride?: T;
  stripeAccountId?: T;
  stripeAccountStatus?: T;
  stripeDetailsSubmitted?: T;
  stripeChargesEnabled?: T;
  stripePayoutsEnabled?: T;
  apiKey?: T;
  rbPayloadTenantId?: T;
  rbPayloadApiKey?: T;
  rbPayloadSyncStatus?: T;
  rbPayloadSyncError?: T;
  phone?: T;
  email?: T;
  description?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  businessHours?:
    | T
    | {
        monday?:
          | T
          | {
              enabled?: T;
              open?: T;
              close?: T;
            };
        tuesday?:
          | T
          | {
              enabled?: T;
              open?: T;
              close?: T;
            };
        wednesday?:
          | T
          | {
              enabled?: T;
              open?: T;
              close?: T;
            };
        thursday?:
          | T
          | {
              enabled?: T;
              open?: T;
              close?: T;
            };
        friday?:
          | T
          | {
              enabled?: T;
              open?: T;
              close?: T;
            };
        saturday?:
          | T
          | {
              enabled?: T;
              open?: T;
              close?: T;
            };
        sunday?:
          | T
          | {
              enabled?: T;
              open?: T;
              close?: T;
            };
      };
  serviceArea?:
    | T
    | {
        radius?: T;
        unit?: T;
        zipCodes?:
          | T
          | {
              code?: T;
              id?: T;
            };
      };
  branding?:
    | T
    | {
        businessName?: T;
        tagline?: T;
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
        emailHeaderBg?: T;
        emailButtonColor?: T;
        emailFooter?: T;
        invoiceHeader?: T;
        termsAndConditions?: T;
        safetyGuidelines?: T;
      };
  website?:
    | T
    | {
        enabled?: T;
        templateId?: T;
        heroTitle?: T;
        heroSubtitle?: T;
        heroImage?: T;
        aboutTitle?: T;
        aboutContent?: T;
        showServices?: T;
        servicesTitle?: T;
        showTestimonials?: T;
        testimonials?:
          | T
          | {
              name?: T;
              content?: T;
              rating?: T;
              id?: T;
            };
        showGallery?: T;
        galleryImages?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        ctaText?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              keywords?: T;
            };
      };
  websiteBuilder?: T;
  customWebsite?:
    | T
    | {
        requested?: T;
        status?: T;
        setupPaidAt?: T;
        monthlyStartedAt?: T;
      };
  settings?:
    | T
    | {
        timezone?: T;
        currency?: T;
        locale?: T;
        bookingSettings?:
          | T
          | {
              leadTime?: T;
              maxAdvanceBooking?: T;
              cancellationPolicy?: T;
              requireApproval?: T;
              depositPercentage?: T;
            };
        deliverySettings?:
          | T
          | {
              deliveryRadius?: T;
              baseDeliveryFee?: T;
              setupTime?: T;
              pickupTime?: T;
            };
        notificationSettings?:
          | T
          | {
              emailNewBooking?: T;
              emailCancellation?: T;
              emailPayment?: T;
              emailReminder?: T;
              emailDailySummary?: T;
              inAppNewBooking?: T;
              inAppCancellation?: T;
              inAppPayment?: T;
              inAppReminder?: T;
              reminderTiming?: T;
            };
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  description?: T;
  isSystemRole?: T;
  permissions?:
    | T
    | {
        key?: T;
        id?: T;
      };
  color?: T;
  memberCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  image?: T;
  sortOrder?: T;
  isActive?: T;
  itemCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rental-items_select".
 */
export interface RentalItemsSelect<T extends boolean = true> {
  tenantId?: T;
  serialNumber?: T;
  name?: T;
  description?: T;
  category?: T;
  categoryId?: T;
  images?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        hourlyRate?: T;
        dailyRate?: T;
        weekendRate?: T;
        weeklyRate?: T;
      };
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  capacity?: T;
  ageRange?:
    | T
    | {
        minAge?: T;
        maxAge?: T;
      };
  setupRequirements?:
    | T
    | {
        spaceRequired?: T;
        powerRequired?: T;
        waterRequired?: T;
        surfaceType?: T;
        setupNotes?: T;
      };
  quantity?: T;
  isActive?: T;
  featured?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  rbPayloadServiceId?: T;
  syncStatus?: T;
  lastSyncedAt?: T;
  syncError?: T;
  hasVariations?: T;
  variationAttributes?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  lastMaintenanceDate?: T;
  nextMaintenanceDate?: T;
  maintenanceStatus?: T;
  maintenanceNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variations_select".
 */
export interface VariationsSelect<T extends boolean = true> {
  tenantId?: T;
  rentalItemId?: T;
  name?: T;
  sku?: T;
  attributes?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  pricingType?: T;
  priceAdjustment?: T;
  overridePrice?:
    | T
    | {
        hourlyRate?: T;
        dailyRate?: T;
        weekendRate?: T;
        weeklyRate?: T;
      };
  quantity?: T;
  trackInventory?: T;
  images?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  tenantId?: T;
  rentalItems?:
    | T
    | {
        rentalItemId?: T;
        quantity?: T;
        price?: T;
        id?: T;
      };
  addOns?:
    | T
    | {
        name?: T;
        price?: T;
        quantity?: T;
        id?: T;
      };
  customerId?: T;
  startDate?: T;
  endDate?: T;
  deliveryTime?: T;
  pickupTime?: T;
  deliveryAddress?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        specialInstructions?: T;
      };
  status?: T;
  totalPrice?: T;
  depositPaid?: T;
  balanceDue?: T;
  paymentStatus?: T;
  notes?: T;
  internalNotes?: T;
  reminderSent?: T;
  reminderSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  email?: T;
  phone?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zipCode?: T;
      };
  notes?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  totalBookings?: T;
  rbPayloadCustomerId?: T;
  syncStatus?: T;
  lastSyncedAt?: T;
  syncError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability_select".
 */
export interface AvailabilitySelect<T extends boolean = true> {
  tenantId?: T;
  rentalItemId?: T;
  startDate?: T;
  endDate?: T;
  reason?: T;
  notes?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  price?: T;
  transactionFee?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  limits?:
    | T
    | {
        maxItems?: T;
        maxBookings?: T;
        maxUsers?: T;
      };
  featureFlags?:
    | T
    | {
        websiteBuilder?: T;
        customRoles?: T;
        customWebsite?: T;
        prioritySupport?: T;
        whiteLabel?: T;
        apiAccess?: T;
      };
  stripePriceId?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  tenantId?: T;
  plan?: T;
  status?: T;
  stripeSubscriptionId?: T;
  stripeCustomerId?: T;
  stripePriceId?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  cancelAtPeriodEnd?: T;
  canceledAt?: T;
  trialStart?: T;
  trialEnd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-units_select".
 */
export interface InventoryUnitsSelect<T extends boolean = true> {
  tenantId?: T;
  rentalItem?: T;
  label?: T;
  serialNumber?: T;
  barcode?: T;
  status?: T;
  condition?: T;
  notes?: T;
  purchaseDate?: T;
  purchasePrice?: T;
  lastMaintenanceDate?: T;
  nextMaintenanceDate?: T;
  maintenanceStatus?: T;
  maintenanceNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bundles_select".
 */
export interface BundlesSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  description?: T;
  items?:
    | T
    | {
        rentalItem?: T;
        quantity?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        type?: T;
        fixedPrice?: T;
        discountPercent?: T;
      };
  image?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "add-ons_select".
 */
export interface AddOnsSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  description?: T;
  icon?: T;
  category?: T;
  pricing?:
    | T
    | {
        type?: T;
        amount?: T;
      };
  required?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  tenantId?: T;
  booking?: T;
  amount?: T;
  currency?: T;
  status?: T;
  refundAmount?: T;
  refundReason?: T;
  stripePaymentIntentId?: T;
  stripeCheckoutSessionId?: T;
  stripeChargeId?: T;
  stripeRefundId?: T;
  platformFee?: T;
  stripeFee?: T;
  platformFeePercent?: T;
  netAmount?: T;
  type?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-endpoints_select".
 */
export interface WebhookEndpointsSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  url?: T;
  secret?: T;
  events?:
    | T
    | {
        event?: T;
        id?: T;
      };
  isActive?: T;
  lastDeliveryAt?: T;
  lastDeliveryStatus?: T;
  failedDeliveriesCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-deliveries_select".
 */
export interface WebhookDeliveriesSelect<T extends boolean = true> {
  endpointId?: T;
  tenantId?: T;
  event?: T;
  payload?: T;
  status?: T;
  attempts?: T;
  maxAttempts?: T;
  nextRetryAt?: T;
  response?:
    | T
    | {
        statusCode?: T;
        body?: T;
        headers?: T;
      };
  error?: T;
  deliveredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  tenantId?: T;
  user?: T;
  type?: T;
  title?: T;
  message?: T;
  read?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  key?: T;
  keyPrefix?: T;
  lastUsed?: T;
  lastRotatedAt?: T;
  isActive?: T;
  scopeType?: T;
  scopes?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collection?: T;
  documentId?: T;
  userId?: T;
  tenantId?: T;
  changes?: T;
  metadata?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  tenantId?: T;
  invoiceNumber?: T;
  bookingId?: T;
  customerId?: T;
  lineItems?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitPrice?: T;
        total?: T;
        id?: T;
      };
  subtotal?: T;
  taxAmount?: T;
  discountAmount?: T;
  totalAmount?: T;
  status?: T;
  dueDate?: T;
  paidAt?: T;
  pdfUrl?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts_select".
 */
export interface ContractsSelect<T extends boolean = true> {
  tenantId?: T;
  contractNumber?: T;
  bookingId?: T;
  customerId?: T;
  type?: T;
  content?: T;
  status?: T;
  sentAt?: T;
  signedAt?: T;
  signatureUrl?: T;
  signerName?: T;
  signerIP?: T;
  pdfUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-templates_select".
 */
export interface ContractTemplatesSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  templateType?: T;
  description?: T;
  content?: T;
  variables?:
    | T
    | {
        key?: T;
        description?: T;
        id?: T;
      };
  isDefault?: T;
  requiresSignature?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-records_select".
 */
export interface MaintenanceRecordsSelect<T extends boolean = true> {
  tenantId?: T;
  rentalItem?: T;
  inventoryUnit?: T;
  type?: T;
  description?: T;
  scheduledDate?: T;
  completedDate?: T;
  status?: T;
  performedBy?: T;
  cost?: T;
  notes?: T;
  checklist?:
    | T
    | {
        task?: T;
        completed?: T;
        notes?: T;
        id?: T;
      };
  photos?:
    | T
    | {
        url?: T;
        caption?: T;
        type?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        url?: T;
        name?: T;
        type?: T;
        id?: T;
      };
  nextMaintenanceDate?: T;
  rbPayloadBlackoutId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-schedules_select".
 */
export interface MaintenanceSchedulesSelect<T extends boolean = true> {
  tenantId?: T;
  rentalItem?: T;
  name?: T;
  frequency?: T;
  frequencyValue?: T;
  maintenanceType?: T;
  checklist?:
    | T
    | {
        task?: T;
        required?: T;
        id?: T;
      };
  instructions?: T;
  estimatedDuration?: T;
  reminderDaysBefore?: T;
  isActive?: T;
  lastCompletedDate?: T;
  nextDueDate?: T;
  rentalCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  tenantId?: T;
  templateKey?: T;
  name?: T;
  subject?: T;
  htmlBody?: T;
  textBody?: T;
  isActive?: T;
  variables?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  content?: T;
  requiresSignature?: T;
  isDefault?: T;
  isActive?: T;
  version?: T;
  effectiveDate?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signed-documents_select".
 */
export interface SignedDocumentsSelect<T extends boolean = true> {
  displayTitle?: T;
  document?: T;
  documentType?: T;
  documentVersion?: T;
  booking?: T;
  customer?: T;
  signerInfo?:
    | T
    | {
        signerName?: T;
        signerEmail?: T;
        signerPhone?: T;
      };
  signerName?: T;
  signedContent?: T;
  signature?:
    | T
    | {
        type?: T;
        data?: T;
        fontFamily?: T;
      };
  metadata?:
    | T
    | {
        signedAt?: T;
        ipAddress?: T;
        userAgent?: T;
        consentGiven?: T;
      };
  signedAt?: T;
  status?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-webhook-events_select".
 */
export interface StripeWebhookEventsSelect<T extends boolean = true> {
  stripeEventId?: T;
  eventType?: T;
  processedAt?: T;
  eventCreatedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-transactions_select".
 */
export interface PlatformTransactionsSelect<T extends boolean = true> {
  type?: T;
  tenantId?: T;
  bookingId?: T;
  subscriptionId?: T;
  originalTransactionId?: T;
  stripePaymentIntentId?: T;
  stripeChargeId?: T;
  stripeTransferId?: T;
  grossAmount?: T;
  stripeFee?: T;
  platformFee?: T;
  platformFeePercent?: T;
  netAmount?: T;
  status?: T;
  refundedAmount?: T;
  refundedAt?: T;
  periodMonth?: T;
  periodYear?: T;
  taxYear?: T;
  metadata?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests_select".
 */
export interface QuoteRequestsSelect<T extends boolean = true> {
  tenantId?: T;
  status?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  eventType?: T;
  eventDate?: T;
  eventStartTime?: T;
  eventEndTime?: T;
  guestCount?: T;
  venueType?: T;
  ageRange?: T;
  fulfillmentType?: T;
  deliveryAddress?: T;
  budgetRange?: T;
  productsRequested?: T;
  additionalServices?: T;
  specialRequests?: T;
  attachments?: T;
  response?:
    | T
    | {
        totalAmount?: T;
        message?: T;
        validityDays?: T;
        termsConditions?: T;
        respondedAt?: T;
        respondedBy?: T;
      };
  adminNotes?: T;
  convertedBookingId?: T;
  source?: T;
  clientIP?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global platform configuration and maintenance settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-settings".
 */
export interface PlatformSetting {
  id: number;
  /**
   * Configure platform-wide maintenance mode
   */
  maintenanceMode?: {
    /**
     * Enable maintenance mode (blocks all non-admin users)
     */
    enabled?: boolean | null;
    /**
     * Message displayed to users during maintenance
     */
    message?: string | null;
    /**
     * Expected end time of maintenance (optional)
     */
    endTime?: string | null;
    /**
     * IP addresses allowed to access during maintenance (optional)
     */
    allowedIPs?:
      | {
          ip: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Platform-wide announcements and notifications
   */
  platformAnnouncements?: {
    /**
     * Show announcement banner to all users
     */
    enabled?: boolean | null;
    /**
     * Announcement message
     */
    message?: string | null;
    /**
     * Announcement type/color
     */
    type?: ('info' | 'warning' | 'success' | 'error') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-settings_select".
 */
export interface PlatformSettingsSelect<T extends boolean = true> {
  maintenanceMode?:
    | T
    | {
        enabled?: T;
        message?: T;
        endTime?: T;
        allowedIPs?:
          | T
          | {
              ip?: T;
              id?: T;
            };
      };
  platformAnnouncements?:
    | T
    | {
        enabled?: T;
        message?: T;
        type?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}