/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    'rental-items': RentalItem;
    bookings: Booking;
    customers: Customer;
    availability: Availability;
    plans: Plan;
    subscriptions: Subscription;
    'inventory-units': InventoryUnit;
    bundles: Bundle;
    'add-ons': AddOn;
    payments: Payment;
    'webhook-endpoints': WebhookEndpoint;
    notifications: Notification;
    'api-keys': ApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'rental-items': RentalItemsSelect<false> | RentalItemsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    availability: AvailabilitySelect<false> | AvailabilitySelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'inventory-units': InventoryUnitsSelect<false> | InventoryUnitsSelect<true>;
    bundles: BundlesSelect<false> | BundlesSelect<true>;
    'add-ons': AddOnsSelect<false> | AddOnsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'webhook-endpoints': WebhookEndpointsSelect<false> | WebhookEndpointsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The tenant this user belongs to (not required for super admins)
   */
  tenantId?: (number | null) | Tenant;
  /**
   * User role and permissions level
   */
  role: 'super_admin' | 'tenant_admin' | 'staff' | 'customer';
  profile?: {
    /**
     * Full name
     */
    name?: string | null;
    /**
     * Phone number
     */
    phone?: string | null;
    /**
     * Profile picture
     */
    avatar?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Business or organization name
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., jump-for-joy-rentals)
   */
  slug: string;
  /**
   * Custom domain (e.g., rentals.jumpforjoy.com)
   */
  domain?: string | null;
  /**
   * Company logo for branding
   */
  logo?: (number | null) | Media;
  /**
   * Subscription plan tier
   */
  plan: 'free' | 'growth' | 'pro' | 'scale';
  /**
   * Stripe Connect account ID
   */
  stripeAccountId?: string | null;
  /**
   * Stripe Connect account status
   */
  stripeAccountStatus?: ('pending' | 'active' | 'restricted' | 'disabled') | null;
  /**
   * Whether Stripe onboarding is complete
   */
  stripeDetailsSubmitted?: boolean | null;
  /**
   * Whether the account can accept charges
   */
  stripeChargesEnabled?: boolean | null;
  /**
   * Whether the account can receive payouts
   */
  stripePayoutsEnabled?: boolean | null;
  /**
   * API key for widget authentication
   */
  apiKey: string;
  settings?: {
    timezone?: ('America/New_York' | 'America/Chicago' | 'America/Denver' | 'America/Los_Angeles' | 'UTC') | null;
    currency?: ('USD' | 'EUR' | 'GBP' | 'CAD') | null;
    locale?: ('en-US' | 'en-GB' | 'es-ES' | 'fr-FR') | null;
    bookingSettings?: {
      /**
       * Minimum hours in advance for bookings
       */
      leadTime?: number | null;
      /**
       * Maximum days in advance for bookings
       */
      maxAdvanceBooking?: number | null;
      /**
       * Cancellation policy text shown to customers
       */
      cancellationPolicy?: string | null;
      /**
       * Bookings require manual approval
       */
      requireApproval?: boolean | null;
      /**
       * Required deposit percentage (0-100)
       */
      depositPercentage?: number | null;
    };
    /**
     * Delivery and setup settings
     */
    deliverySettings?: {
      /**
       * Maximum delivery distance in miles
       */
      deliveryRadius?: number | null;
      /**
       * Base delivery fee
       */
      baseDeliveryFee?: number | null;
      /**
       * Average setup time in minutes
       */
      setupTime?: number | null;
      /**
       * Average pickup time in minutes
       */
      pickupTime?: number | null;
    };
  };
  /**
   * Tenant account status
   */
  status: 'active' | 'suspended' | 'deleted';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Leave empty for platform-wide assets
   */
  tenantId?: (number | null) | Tenant;
  /**
   * Alt text for accessibility
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rental-items".
 */
export interface RentalItem {
  id: number;
  /**
   * The tenant this rental item belongs to
   */
  tenantId: number | Tenant;
  /**
   * Rental item name (e.g., "Princess Castle Bounce House", "Water Slide Deluxe")
   */
  name: string;
  /**
   * Detailed description of the rental item
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Category of rental item
   */
  category:
    | 'bounce_house'
    | 'water_slide'
    | 'combo_unit'
    | 'obstacle_course'
    | 'interactive_game'
    | 'tent_canopy'
    | 'table_chair'
    | 'concession'
    | 'other';
  /**
   * Product images (first image is primary). Upload via Bunny CDN.
   */
  images?:
    | {
        /**
         * Image URL (Bunny CDN or external)
         */
        url: string;
        /**
         * Alt text for accessibility
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  pricing: {
    /**
     * Hourly rental rate (optional)
     */
    hourlyRate?: number | null;
    /**
     * Full day rental rate
     */
    dailyRate: number;
    /**
     * Weekend rental rate (Friday-Sunday)
     */
    weekendRate?: number | null;
    /**
     * Weekly rental rate (7 days)
     */
    weeklyRate?: number | null;
  };
  dimensions?: {
    /**
     * Length in feet
     */
    length?: number | null;
    /**
     * Width in feet
     */
    width?: number | null;
    /**
     * Height in feet
     */
    height?: number | null;
  };
  /**
   * Maximum number of people/children
   */
  capacity?: number | null;
  ageRange?: {
    /**
     * Minimum age
     */
    minAge?: number | null;
    /**
     * Maximum age
     */
    maxAge?: number | null;
  };
  setupRequirements?: {
    /**
     * Space requirements (e.g., "15x15 flat area")
     */
    spaceRequired?: string | null;
    /**
     * Requires electrical outlet
     */
    powerRequired?: boolean | null;
    /**
     * Requires water hookup
     */
    waterRequired?: boolean | null;
    /**
     * Suitable surface types
     */
    surfaceType?: ('grass' | 'concrete' | 'asphalt' | 'indoor' | 'any') | null;
    /**
     * Additional setup instructions
     */
    setupNotes?: string | null;
  };
  /**
   * Number of units available
   */
  quantity?: number | null;
  /**
   * Is this item currently available for rental?
   */
  isActive?: boolean | null;
  /**
   * Feature this item on homepage
   */
  featured?: boolean | null;
  /**
   * Tags for filtering (e.g., "outdoor", "princess theme", "wet")
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ID of corresponding service in rb-payload (for 2-way sync)
   */
  rbPayloadServiceId?: number | null;
  /**
   * Status of sync with rb-payload
   */
  syncStatus?: ('pending' | 'synced' | 'failed' | 'out_of_sync') | null;
  /**
   * Last successful sync with rb-payload
   */
  lastSyncedAt?: string | null;
  /**
   * Last sync error message
   */
  syncError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  tenantId: number | Tenant;
  /**
   * The rental item being booked
   */
  rentalItemId: number | RentalItem;
  /**
   * Customer who made the booking
   */
  customerId: number | Customer;
  /**
   * Rental start date and time
   */
  startDate: string;
  /**
   * Rental end date and time
   */
  endDate: string;
  deliveryAddress: {
    /**
     * Delivery street address
     */
    street: string;
    /**
     * City
     */
    city: string;
    /**
     * State/Province
     */
    state: string;
    /**
     * ZIP/Postal code
     */
    zipCode: string;
    /**
     * Special delivery/setup instructions
     */
    specialInstructions?: string | null;
  };
  /**
   * Booking status
   */
  status: 'pending' | 'confirmed' | 'delivered' | 'completed' | 'cancelled';
  /**
   * Total rental price
   */
  totalPrice: number;
  /**
   * Deposit amount paid
   */
  depositPaid?: number | null;
  /**
   * Remaining balance due
   */
  balanceDue?: number | null;
  /**
   * Payment status
   */
  paymentStatus?: ('unpaid' | 'deposit_paid' | 'paid_full' | 'refunded') | null;
  /**
   * Special instructions or notes
   */
  notes?: string | null;
  /**
   * Internal staff notes (not visible to customer)
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  tenantId: number | Tenant;
  /**
   * Customer full name
   */
  name: string;
  /**
   * Customer email address
   */
  email: string;
  /**
   * Customer phone number
   */
  phone: string;
  address?: {
    /**
     * Street address
     */
    street?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State/Province
     */
    state?: string | null;
    /**
     * ZIP/Postal code
     */
    zipCode?: string | null;
  };
  /**
   * Internal notes about this customer
   */
  notes?: string | null;
  /**
   * Tags for customer segmentation (e.g., "VIP", "Regular", "Corporate")
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Total number of bookings
   */
  totalBookings?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage blackout dates and maintenance windows for rental items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability".
 */
export interface Availability {
  id: number;
  /**
   * The tenant this availability rule belongs to
   */
  tenantId: number | Tenant;
  /**
   * The rental item this blackout applies to
   */
  rentalItemId: number | RentalItem;
  /**
   * Blackout start date and time
   */
  startDate: string;
  /**
   * Blackout end date and time
   */
  endDate: string;
  /**
   * Reason for unavailability
   */
  reason: 'maintenance' | 'repair' | 'booked' | 'seasonal' | 'other';
  /**
   * Additional notes about this blackout period
   */
  notes?: string | null;
  /**
   * Is this blackout currently active?
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  /**
   * Plan name (e.g., "Free", "Pro", "Enterprise")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "free", "pro", "enterprise")
   */
  slug: string;
  /**
   * Monthly price in cents (e.g., 2900 for $29.00)
   */
  price: number;
  /**
   * Transaction fee percentage (e.g., 6 for 6%)
   */
  transactionFee: number;
  /**
   * List of features included in this plan
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  limits: {
    /**
     * Maximum number of rental items allowed
     */
    maxItems: number;
    /**
     * Maximum number of bookings per month
     */
    maxBookings: number;
  };
  /**
   * Is this plan available for new signups?
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  /**
   * The tenant this subscription belongs to
   */
  tenantId: number | Tenant;
  /**
   * Subscription plan
   */
  plan: number | Plan;
  /**
   * Subscription status
   */
  status: 'active' | 'canceled' | 'past_due' | 'trialing';
  /**
   * Stripe subscription ID
   */
  stripeSubscriptionId?: string | null;
  /**
   * Current billing period start date
   */
  currentPeriodStart?: string | null;
  /**
   * Current billing period end date
   */
  currentPeriodEnd?: string | null;
  /**
   * Cancel subscription at end of current period
   */
  cancelAtPeriodEnd?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-units".
 */
export interface InventoryUnit {
  id: number;
  /**
   * The tenant this inventory unit belongs to
   */
  tenantId: number | Tenant;
  /**
   * The rental item this unit represents
   */
  rentalItem: number | RentalItem;
  /**
   * Unit identifier (e.g., "Unit #1", "Castle A")
   */
  label: string;
  /**
   * Manufacturer serial number
   */
  serialNumber?: string | null;
  /**
   * Barcode for scanning
   */
  barcode?: string | null;
  /**
   * Current status of the unit
   */
  status: 'available' | 'rented' | 'maintenance' | 'retired';
  /**
   * Physical condition of the unit
   */
  condition: 'excellent' | 'good' | 'fair' | 'poor';
  /**
   * General notes about this unit
   */
  notes?: string | null;
  /**
   * Date of purchase
   */
  purchaseDate?: string | null;
  /**
   * Purchase price (for asset tracking)
   */
  purchasePrice?: number | null;
  /**
   * Date of last maintenance/inspection
   */
  lastMaintenanceDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bundles".
 */
export interface Bundle {
  id: number;
  /**
   * The tenant this bundle belongs to
   */
  tenantId: number | Tenant;
  /**
   * Bundle name (e.g., "Birthday Party Package", "Ultimate Party Bundle")
   */
  name: string;
  /**
   * Detailed description of the bundle
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Items included in this bundle
   */
  items: {
    /**
     * Rental item included in bundle
     */
    rentalItem: number | RentalItem;
    /**
     * Quantity of this item
     */
    quantity: number;
    id?: string | null;
  }[];
  pricing: {
    /**
     * Pricing strategy for this bundle
     */
    type: 'fixed' | 'calculated' | 'discounted';
    /**
     * Fixed price (if pricing type is "fixed")
     */
    fixedPrice?: number | null;
    /**
     * Discount percentage (if pricing type is "discounted")
     */
    discountPercent?: number | null;
  };
  /**
   * Bundle image
   */
  image?: (number | null) | Media;
  /**
   * Feature this bundle on homepage
   */
  featured?: boolean | null;
  /**
   * Is this bundle currently available?
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "add-ons".
 */
export interface AddOn {
  id: number;
  /**
   * The tenant this add-on belongs to
   */
  tenantId: number | Tenant;
  /**
   * Add-on name (e.g., "Delivery", "Setup", "Generator Rental")
   */
  name: string;
  /**
   * Description of the add-on service
   */
  description?: string | null;
  pricing: {
    /**
     * Pricing calculation method
     */
    type: 'fixed' | 'perItem' | 'perDay';
    /**
     * Price amount
     */
    amount: number;
  };
  /**
   * Is this add-on required for all bookings?
   */
  required?: boolean | null;
  /**
   * Is this add-on currently available?
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  /**
   * The tenant this payment belongs to
   */
  tenantId: number | Tenant;
  /**
   * The booking this payment is for
   */
  booking: number | Booking;
  /**
   * Payment amount in cents (e.g., 5000 for $50.00)
   */
  amount: number;
  /**
   * Currency code
   */
  currency?: string | null;
  /**
   * Payment status
   */
  status: 'pending' | 'succeeded' | 'failed' | 'refunded';
  /**
   * Stripe Payment Intent ID
   */
  stripePaymentIntentId?: string | null;
  /**
   * Stripe Charge ID
   */
  stripeChargeId?: string | null;
  /**
   * Type of payment
   */
  type: 'deposit' | 'balance' | 'full' | 'refund';
  /**
   * Additional payment metadata
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-endpoints".
 */
export interface WebhookEndpoint {
  id: number;
  /**
   * The tenant this webhook endpoint belongs to
   */
  tenantId: number | Tenant;
  /**
   * Webhook endpoint URL
   */
  url: string;
  /**
   * Webhook signing secret for verification
   */
  secret: string;
  /**
   * Events to listen for
   */
  events: {
    event:
      | 'booking.created'
      | 'booking.confirmed'
      | 'booking.cancelled'
      | 'booking.delivered'
      | 'booking.completed'
      | 'payment.succeeded'
      | 'payment.failed'
      | 'payment.refunded';
    id?: string | null;
  }[];
  /**
   * Is this webhook endpoint active?
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * The tenant this notification belongs to
   */
  tenantId: number | Tenant;
  /**
   * User to notify (leave empty for all users in tenant)
   */
  user?: (number | null) | User;
  /**
   * Type of notification
   */
  type:
    | 'booking_created'
    | 'booking_confirmed'
    | 'booking_cancelled'
    | 'payment_received'
    | 'payment_failed'
    | 'reminder'
    | 'system';
  /**
   * Notification title
   */
  title: string;
  /**
   * Notification message
   */
  message: string;
  /**
   * Has this notification been read?
   */
  read?: boolean | null;
  /**
   * Additional data (e.g., booking ID, payment amount)
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  /**
   * The tenant this API key belongs to
   */
  tenantId: number | Tenant;
  /**
   * A descriptive name for this API key
   */
  name: string;
  /**
   * The API key value (only shown once at creation)
   */
  key: string;
  /**
   * First 12 characters of the key for identification
   */
  keyPrefix?: string | null;
  /**
   * When this API key was last used
   */
  lastUsed?: string | null;
  /**
   * Is this API key active?
   */
  isActive?: boolean | null;
  /**
   * Specific permissions for this API key (empty = full access)
   */
  permissions?:
    | {
        permission?:
          | (
              | 'inventory:read'
              | 'inventory:write'
              | 'bookings:read'
              | 'bookings:write'
              | 'customers:read'
              | 'customers:write'
              | 'reports:read'
              | 'webhooks:manage'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional expiration date for this API key
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'rental-items';
        value: number | RentalItem;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'availability';
        value: number | Availability;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'inventory-units';
        value: number | InventoryUnit;
      } | null)
    | ({
        relationTo: 'bundles';
        value: number | Bundle;
      } | null)
    | ({
        relationTo: 'add-ons';
        value: number | AddOn;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'webhook-endpoints';
        value: number | WebhookEndpoint;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  tenantId?: T;
  role?: T;
  profile?:
    | T
    | {
        name?: T;
        phone?: T;
        avatar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenantId?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  logo?: T;
  plan?: T;
  stripeAccountId?: T;
  stripeAccountStatus?: T;
  stripeDetailsSubmitted?: T;
  stripeChargesEnabled?: T;
  stripePayoutsEnabled?: T;
  apiKey?: T;
  settings?:
    | T
    | {
        timezone?: T;
        currency?: T;
        locale?: T;
        bookingSettings?:
          | T
          | {
              leadTime?: T;
              maxAdvanceBooking?: T;
              cancellationPolicy?: T;
              requireApproval?: T;
              depositPercentage?: T;
            };
        deliverySettings?:
          | T
          | {
              deliveryRadius?: T;
              baseDeliveryFee?: T;
              setupTime?: T;
              pickupTime?: T;
            };
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rental-items_select".
 */
export interface RentalItemsSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  description?: T;
  category?: T;
  images?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        hourlyRate?: T;
        dailyRate?: T;
        weekendRate?: T;
        weeklyRate?: T;
      };
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  capacity?: T;
  ageRange?:
    | T
    | {
        minAge?: T;
        maxAge?: T;
      };
  setupRequirements?:
    | T
    | {
        spaceRequired?: T;
        powerRequired?: T;
        waterRequired?: T;
        surfaceType?: T;
        setupNotes?: T;
      };
  quantity?: T;
  isActive?: T;
  featured?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  rbPayloadServiceId?: T;
  syncStatus?: T;
  lastSyncedAt?: T;
  syncError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  tenantId?: T;
  rentalItemId?: T;
  customerId?: T;
  startDate?: T;
  endDate?: T;
  deliveryAddress?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        specialInstructions?: T;
      };
  status?: T;
  totalPrice?: T;
  depositPaid?: T;
  balanceDue?: T;
  paymentStatus?: T;
  notes?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  email?: T;
  phone?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zipCode?: T;
      };
  notes?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  totalBookings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability_select".
 */
export interface AvailabilitySelect<T extends boolean = true> {
  tenantId?: T;
  rentalItemId?: T;
  startDate?: T;
  endDate?: T;
  reason?: T;
  notes?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  price?: T;
  transactionFee?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  limits?:
    | T
    | {
        maxItems?: T;
        maxBookings?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  tenantId?: T;
  plan?: T;
  status?: T;
  stripeSubscriptionId?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  cancelAtPeriodEnd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-units_select".
 */
export interface InventoryUnitsSelect<T extends boolean = true> {
  tenantId?: T;
  rentalItem?: T;
  label?: T;
  serialNumber?: T;
  barcode?: T;
  status?: T;
  condition?: T;
  notes?: T;
  purchaseDate?: T;
  purchasePrice?: T;
  lastMaintenanceDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bundles_select".
 */
export interface BundlesSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  description?: T;
  items?:
    | T
    | {
        rentalItem?: T;
        quantity?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        type?: T;
        fixedPrice?: T;
        discountPercent?: T;
      };
  image?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "add-ons_select".
 */
export interface AddOnsSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  description?: T;
  pricing?:
    | T
    | {
        type?: T;
        amount?: T;
      };
  required?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  tenantId?: T;
  booking?: T;
  amount?: T;
  currency?: T;
  status?: T;
  stripePaymentIntentId?: T;
  stripeChargeId?: T;
  type?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-endpoints_select".
 */
export interface WebhookEndpointsSelect<T extends boolean = true> {
  tenantId?: T;
  url?: T;
  secret?: T;
  events?:
    | T
    | {
        event?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  tenantId?: T;
  user?: T;
  type?: T;
  title?: T;
  message?: T;
  read?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  key?: T;
  keyPrefix?: T;
  lastUsed?: T;
  isActive?: T;
  permissions?:
    | T
    | {
        permission?: T;
        id?: T;
      };
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}